import type { Metadata } from "next";
import { Pacifico, Caveat_Brush } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-pacifico'
});

const caveatBrush = Caveat_Brush({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-caveat-brush'
});

export const metadata: Metadata = {
  title: "Mimi's Workshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caveatBrush.variable} ${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
